### ISSUE TITLE
Error while executing at line #74

### ISSUE THREAD

**Issue by SHANKARMB** [smayru/catgan#5]
load MNIST dataset
epoch 1
Traceback (most recent call last):
  File "catgan_train.py", line 164, in <module>
    fake_x=gen(z)
  File "catgan_train.py", line 73, in __call__
    h1=F.leaky_relu(self.bn0(self.l0(z),test),slope=0.1)
TypeError: __call__() takes 2 positional arguments but 3 were given

<br/>
Someone in  other issue page suggested to remove test in func call...
tried it .. but didn't work..

<br/>

Even after making above changes, I get this error..
`load MNIST dataset
epoch 1
Traceback (most recent call last):
  File "catgan_train.py", line 164, in <module>
    fake_x=gen(z)
  File "catgan_train.py", line 74, in __call__
    h2=F.leaky_relu(self.bn1(self.l1(h1),test),slope=0.1)
TypeError: __call__() takes 2 positional arguments but 3 were given
`

<br/>

I removed test from all these 3 line..
<br/>
_h1=F.leaky_relu(self.bn0(self.l0(z)),slope=0.1)
        h2=F.leaky_relu(self.bn1(self.l1(h1)),slope=0.1)
        h3=F.leaky_relu(self.bn2(self.l2(h2)))
        h4=F.sigmoid(self.l3(h3))_
It still gives me this error..
<br/>
load MNIST dataset
epoch 1
Traceback (most recent call last):
  File "catgan_train.py", line 165, in <module>
    fake_y=dis(fake_x)
  File "catgan_train.py", line 117, in __call__
    h1=F.leaky_relu(self.bn0(self.l0(x)+F.gaussian(mu_array2,log_std_array2),test),slope=0.1)
TypeError: __call__() takes 2 positional arguments but 3 were given

<br/>

So I removed test in other calls too... like this..

_h1=F.leaky_relu(self.bn0(self.l0(x)+F.gaussian(mu_array2,log_std_array2)),slope=0.1)
        h2=F.leaky_relu(self.bn1(self.l1(h1)+F.gaussian(mu_array3,log_std_array3)),slope=0.1)
        h3=F.leaky_relu(self.bn2(self.l2(h2)+F.gaussian(mu_array4,log_std_array4)),slope=0.1)
        h4=F.leaky_relu(self.bn3(self.l3(h3)+F.gaussian(mu_array5,log_std_array5)),slope=0.1)
        h5=F.leaky_relu(self.bn4(self.l4(h4)+F.gaussian(mu_array6,log_std_array6)),slope=0.1)
        h6=F.softmax(self.l5(h5))_

<br/>

It gives me this error..

<br/>

load MNIST dataset
epoch 1
Traceback (most recent call last):
  File "catgan_train.py", line 170, in <module>
    o_dis.zero_grads()
AttributeError: 'Adam' object has no attribute 'zero_grads'

**Comment by amen183** [comment]
did you solve this problem?
